import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { apiFetch } from "../lib/api";
import ReceiptPrint from "../components/anim/ReceiptPrint";

function Report() {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [message, setMessage] = useState("");
  const [pdfBusy, setPdfBusy] = useState(false);

  useEffect(() => {
    const loadReport = async () => {
      try {
        const report = await apiFetch(`/api/prediction/${id}`);
        setData(report);
      } catch (err) {
        setMessage(err.message || "Unable to load report.");
      }
    };

    loadReport();
  }, [id]);

  const handleDownloadPdf = async () => {
    if (!data) {
      return;
    }

    try {
      setPdfBusy(true);
      // Lazy-load jspdf so the report page stays light until a PDF is requested.
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "pt", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 48;
      let y = 64;

      doc.setFillColor(16, 34, 23);
      doc.rect(0, 0, pageWidth, 120, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(24);
      doc.text("Khety Crop Health Report", margin, 56);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(214, 227, 217);
      doc.text("Crop diagnostics • precision agriculture", margin, 80);

      y = 160;
      doc.setTextColor(16, 34, 23);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.text("Result", margin, y);
      y += 22;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(16);
      doc.text(data.result || "Not available", margin, y);
      y += 24;
      doc.setFontSize(11);
      doc.setTextColor(90, 107, 98);
      doc.text(
        `Confidence: ${data.confidence ?? 0}%   •   ${new Date(data.createdAt).toLocaleString("en-IN")}`,
        margin,
        y
      );
      y += 34;

      const sections = [
        ["Problem", data.report?.problem],
        ["Cause", data.report?.cause],
        ["Symptoms", data.report?.symptoms],
        ["Damage", data.report?.damage],
        ["Solution", data.report?.solution]
      ];

      sections.forEach(([title, value]) => {
        if (!value) {
          return;
        }

        if (y > 720) {
          doc.addPage();
          y = 64;
        }

        doc.setFillColor(33, 87, 50);
        doc.roundedRect(margin, y, 6, 18, 3, 3, "F");
        doc.setTextColor(16, 34, 23);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.text(title.toUpperCase(), margin + 16, y + 14);
        y += 26;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(60, 74, 66);

        const lines = doc.splitTextToSize(value, pageWidth - margin * 2);
        lines.forEach((line) => {
          if (y > 760) {
            doc.addPage();
            y = 64;
          }
          doc.text(line, margin, y);
          y += 16;
        });
        y += 18;
      });

      doc.setFontSize(9);
      doc.setTextColor(140, 155, 145);
      doc.text(
        "Generated by Khety • Consult a local agricultural expert before taking action.",
        margin,
        doc.internal.pageSize.getHeight() - 36
      );

      const slug = (data.result || "report")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "")
        .slice(0, 40);
      doc.save(`khety-report-${slug}.pdf`);
    } catch (err) {
      console.log("PDF generation error:", err);
      alert("Unable to generate the PDF report. Please try again.");
    } finally {
      setPdfBusy(false);
    }
  };

  if (message) {
    return (
      <div className="min-h-screen px-6 py-8 md:px-10">
        <div className="mx-auto max-w-4xl rounded-2xl bg-rose-50 px-4 py-3 text-sm text-rose-700">
          {message}
        </div>
      </div>
    );
  }

  if (!data) {
    return <p className="p-10 text-sm text-[#607065]">Loading report...</p>;
  }

  return (
    <div className="min-h-screen px-6 py-8 md:px-10">
      <div className="mx-auto max-w-4xl space-y-6">
        <section className="rounded-[32px] border border-[#dbe3d9] bg-white p-8 shadow-[0_20px_60px_rgba(16,34,23,0.06)]">
          <div className="flex flex-col gap-6 md:flex-row md:items-start md:justify-between">
            <div className="min-w-0">
              <p className="text-xs font-bold uppercase tracking-[0.35em] text-[#8a5b21]">
                Detection Report
              </p>

              {/* printed report header — the verdict prints line by line */}
              <div className="mt-4 max-w-sm">
                <ReceiptPrint
                  header="Crop Health Report"
                  footer="Generated by Khety"
                  items={[
                    {
                      label: "Result",
                      text: data.result || "Not available",
                      verdict: true
                    },
                    {
                      label: "Confidence",
                      text: `${data.confidence ?? 0}%`,
                      muted: true
                    },
                    {
                      label: "Scanned",
                      text: new Date(data.createdAt).toLocaleString("en-IN"),
                      muted: true
                    }
                  ]}
                />
              </div>

              <button
                onClick={handleDownloadPdf}
                disabled={pdfBusy}
                className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-[#102217] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#173d24] disabled:bg-[#98aa9d]"
              >
                {pdfBusy ? "Preparing PDF..." : "Download PDF report"}
              </button>
            </div>

            {data.image ? (
              <div className="w-full shrink-0 overflow-hidden rounded-[24px] border border-[#dbe3d9] bg-[#f3f6f1] md:w-64">
                <img
                  src={data.image}
                  alt="Scanned crop leaf"
                  className="h-56 w-full object-cover md:h-52"
                  onError={(event) => {
                    event.currentTarget.style.display = "none";
                  }}
                />
              </div>
            ) : null}
          </div>
        </section>

        <section className="rounded-[32px] border border-[#dbe3d9] bg-white p-8 shadow-[0_20px_60px_rgba(16,34,23,0.06)]">
          <div className="grid gap-5 md:grid-cols-2">
            {[
              ["Problem", data.report?.problem || "No data available"],
              ["Cause", data.report?.cause || "No data available"],
              ["Symptoms", data.report?.symptoms || "No data available"],
              ["Damage", data.report?.damage || "No data available"],
              ["Solution", data.report?.solution || "No data available"]
            ].map(([title, value], index) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ delay: index * 0.12, duration: 0.5, ease: "easeOut" }}
                className={`rounded-3xl border border-[#dbe3d9] p-5 ${
                  title === "Solution" ? "md:col-span-2 bg-[#f7faf5]" : "bg-[#fbfcfa]"
                }`}
              >
                <p className="text-sm font-bold uppercase tracking-[0.2em] text-[#8a5b21]">
                  {title}
                </p>
                <p className="mt-3 text-sm leading-7 text-[#55645b]">{value}</p>
              </motion.div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}

export default Report;
